trigger:
  branches:
    include:
      - main  # Trigger on the main branch. Change this to your branch if needed.

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDirectory: 'build'

jobs:
  - job: BuildAndDeploy
    displayName: 'Build Docusaurus and Deploy to Azure WebApp'
    steps:
    
    # Checkout the repository
    - checkout: self

    # Install dependencies
    - task: NodeTool@0
      inputs:
        versionSpec: '20'  # You can adjust the Node.js version here
        addToPath: true

    - script: |
        npm install
      displayName: 'Install npm dependencies'

    # Build the Docusaurus app
    - script: |
        npm run build
      displayName: 'Build Docusaurus'
