trigger:
  branches:
    include:
      - main  # Trigger on the main branch. Change if needed.

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDirectory: 'build'

jobs:
  - job: BuildAndDeploy
    displayName: 'Build Docusaurus and Deploy to Azure WebApp'
    steps:
    
    # Checkout the repository
    - checkout: self  # Correct syntax for checkout

    # Install dependencies
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'  # Ensure this version is compatible with Docusaurus
        addToPath: true

    - script: |
        npm install
      displayName: 'Install npm dependencies'

    # Build the Docusaurus app
    - script: |
        npm run build
      displayName: 'Build Docusaurus'

    # Deploy to Azure WebApp
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Infotechtion Documentation'  # Replace with your Azure service connection name
        appName: 'iarm-docs'  # Replace with your Azure WebApp name
        package: '$(System.DefaultWorkingDirectory)/$(buildDirectory)'  # Path to the build directory
        deploymentMethod: 'zipDeploy'

    # Optional: Publish build artifacts if needed
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop
